"""Employee profile sections."""

from app.models.hrm import (
    CustomField,
    Dependent,
    EmergencyContact,
    Employee,
    EmployeeContact,
    EmployeeSalary,
    EmployeeSkill,
    ImmigrationRecord,
)
from app.orbit.hrm.resources.factory import crud

EmployeeResource = crud(
    "EmployeeResource",
    model=Employee,
    label="Employee list",
    group="PIM",
    subgroup="",
    data_group="pim",
    icon="heroicon-o-users",
    sort=1,
    fields=("employee_number", "first_name", "last_name", "email", "joined_on"),
    employee_scope="id",
    menu_when="beyond_self",
)
EmployeeContactResource = crud(
    "EmployeeContactResource",
    model=EmployeeContact,
    label="Contacts",
    group="ESS",
    subgroup="Personal",
    data_group="pim",
    icon="heroicon-o-phone",
    sort=2,
    fields=("employee_id", "city", "mobile", "work_email"),
    employee_scope="employee_id",
    nav=False,
)
EmergencyContactResource = crud(
    "EmergencyContactResource",
    model=EmergencyContact,
    label="Emergency contacts",
    group="ESS",
    subgroup="Personal",
    data_group="pim",
    icon="heroicon-o-heart",
    sort=3,
    fields=("employee_id", "name", "relationship", "phone"),
    employee_scope="employee_id",
    nav=False,
)
DependentResource = crud(
    "DependentResource",
    model=Dependent,
    label="Dependents",
    group="ESS",
    subgroup="Personal",
    data_group="pim",
    icon="heroicon-o-user",
    sort=4,
    fields=("employee_id", "name", "relationship", "date_of_birth"),
    employee_scope="employee_id",
    nav=False,
)
ImmigrationRecordResource = crud(
    "ImmigrationRecordResource",
    model=ImmigrationRecord,
    label="Immigration",
    group="ESS",
    subgroup="Personal",
    data_group="pim",
    icon="heroicon-o-identification",
    sort=5,
    fields=("employee_id", "document_type", "number", "expires_on"),
    employee_scope="employee_id",
    nav=False,
)
EmployeeSalaryResource = crud(
    "EmployeeSalaryResource",
    model=EmployeeSalary,
    label="Salaries",
    group="ESS",
    subgroup="Job",
    data_group="payroll",
    icon="heroicon-o-banknotes",
    sort=6,
    fields=("employee_id", "amount", "currency"),
    employee_scope="employee_id",
    nav=False,
)
EmployeeSkillResource = crud(
    "EmployeeSkillResource",
    model=EmployeeSkill,
    label="Employee skills",
    group="ESS",
    subgroup="Qualifications",
    data_group="pim",
    icon="heroicon-o-academic-cap",
    sort=7,
    fields=("employee_id", "skill_id", "years"),
    employee_scope="employee_id",
    nav=False,
)
CustomFieldResource = crud(
    "CustomFieldResource",
    model=CustomField,
    label="Custom fields",
    group="PIM",
    subgroup="Configuration",
    data_group="pim",
    modal=True,
    icon="heroicon-o-adjustments-horizontal",
    sort=8,
    fields=("name", "screen"),
    menu_when="company",
)
